AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  validatingwebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::820537372947:role/service-role/validating_webhook-role-molxb9sh
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /validating_webhook
            Method: ANY
